import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Graduate,graduatesApi} from '../lib/graduates';
import {safeUrl} from '../lib/commerce';
export default function GraduatesTable({year}:{year?:number}){
 const [items,setItems]=useState<Graduate[]>([]),[years,setYears]=useState<number[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;setLoading(true);setError('');graduatesApi(`/graduates${year?`?year=${year}`:''}`).then(d=>{if(alive){setItems(d.items);setYears(d.years.map((x:{year:number})=>x.year));}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[year]);
 const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const visible=items.filter(x=>(!filter||String(x.graduation_year)===filter)&&normalize(`${x.name} ${x.institute}`).includes(normalize(query)));
 return <section className="max-w-7xl mx-auto px-4 sm:px-6 py-12"><h2 className="text-3xl text-navy font-800 mb-3">Egresados {year||''}</h2><p className="text-muted mb-6">Consultá los egresados y descargá sus certificados.</p><div className="flex flex-wrap gap-3 mb-6"><input aria-label="Buscar egresado" placeholder="Buscar por nombre o instituto" value={query} onChange={e=>setQuery(e.target.value)} className="border rounded-lg p-3 flex-1 min-w-48"/>{!year&&<select aria-label="Año de egreso" value={filter} onChange={e=>setFilter(e.target.value)} className="border rounded-lg p-3"><option value="">Todos los años</option>{years.map(y=><option key={y}>{y}</option>)}</select>}</div>{year&&<Link to="/ibaa/egresados" className="text-brand inline-block mb-4">Ver todas las promociones →</Link>}{error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p>Cargando egresados…</p>:!error&&<><p className="text-muted text-sm mb-3">{visible.length} egresados</p><div className="overflow-x-auto border border-border rounded-xl"><table className="w-full text-left text-sm"><caption className="sr-only">Egresados {year||'del IBAA'}</caption><thead className="bg-navy text-white"><tr>{['Instituto','Nombre','Año','Promedio final','Certificado'].map(h=><th key={h} scope="col" className="p-4">{h}</th>)}</tr></thead><tbody>{visible.map(x=><tr key={x.id} className="border-t border-border even:bg-surface"><td className="p-4">{x.institute}</td><td className="p-4 font-600">{x.name}</td><td className="p-4"><Link to={`/ibaa/egresados-${x.graduation_year}/`} className="text-brand">{x.graduation_year}</Link></td><td className="p-4">{x.average==null?'—':Number(x.average).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td className="p-4">{safeUrl(x.certificate_url)?<a href={safeUrl(x.certificate_url)} target="_blank" rel="noreferrer" className="text-brand underline" aria-label={`Certificado de ${x.name}`}>Ver certificado</a>:'—'}</td></tr>)}</tbody></table></div>{!visible.length&&<p className="mt-4">{query?'No hay coincidencias.':'Todavía no hay egresados publicados para esta promoción.'}</p>}</>}</section>;
}
